server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri:
              lb://USER-SERVICE
            predicates:
              - Path=/auth/**,/users/**,/api/users/**
              - Path=/

          - id: TASK-SERVICE
            uri:
              lb://TASK-SERVICE
            predicates:
              - Path=/tasks/**, /api/tasks/**

          - id: SUBMISSION-SERVICE
            uri:
              lb://SUBMISSION-SERVICE
            predicates:
              - Path=/submissions/**, /api/submissions/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          cors-configuration:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/